// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwytguqfpnoxnelbvded.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eXRndXFmcG5veG5lbGJ2ZGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzMTQ3NDAsImV4cCI6MjA5Mzg5MDc0MH0.4TRwEG7X8OdXAlskQNzFwo2Yu4GdeNYTjyVcu0IRUco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});